feature/RI- 982
A2O-Dev/pfr-test-automation pull request #18
Opened 2023-04-20 23:51 UTC by Giselle026

2023-04-21 15:11 UTC, cancioalmaraza2o requested changes

2023-04-21 15:11 UTC, cancioalmaraza2o commented on tests/dictionaries/selectors.ts
> +// Exporta el diccionario de selectores como un objeto con una propiedad "selectors"
Comentario innecesario

2023-04-21 15:11 UTC, cancioalmaraza2o commented on tests/dictionaries/selectors.ts
> + //login
Comentario innecesario

2023-04-21 15:11 UTC, cancioalmaraza2o commented on tests/dictionaries/selectors.ts
> +// Exporta el objeto completo, si lo desea
Comentario innecesario

2023-04-21 15:11 UTC, cancioalmaraza2o commented on tests/dictionaries/selectors.ts
> +    bntLogin           :'input[type="submit"]'
bntLogin?

No debería ser "**btnLogin**" ???

2023-04-21 15:11 UTC, cancioalmaraza2o commented on tests/login/loginSiteAdmin.spec.ts
> +// @ts-ignore
Debido a qué se ignora este error?

2023-04-21 15:11 UTC, cancioalmaraza2o commented on tests/login/loginSiteAdmin.spec.ts
> +    await expect($(selectors.userName)).toBeExisting()
Este await, es necesario? la ejecución de esta línea es asíncrona?

2023-04-21 15:11 UTC, cancioalmaraza2o commented on tests/login/loginSiteAdmin.spec.ts
> +    await expect($(selectors.password)).toBeExisting()
Este await, es necesario? la ejecución de esta línea es asíncrona?

2023-04-21 15:11 UTC, cancioalmaraza2o commented on tests/login/loginSiteAdmin.spec.ts
> +    await $(selectors.userName).setValue(env.SITEADMIN_USERNAME)
Este await, es necesario? la ejecución de esta línea es asíncrona?

2023-04-21 15:11 UTC, cancioalmaraza2o commented on tests/login/loginSiteAdmin.spec.ts
> +    await $(selectors.password).setValue(env.SITEADMIN_PASSWORD)
Este await, es necesario? la ejecución de esta línea es asíncrona?

2023-04-21 15:11 UTC, cancioalmaraza2o commented on tests/login/loginSiteAdmin.spec.ts
> +    await $(selectors.bntLogin).click()
Este await, es necesario? la ejecución de esta línea es asíncrona?

2023-04-21 22:40 UTC, Giselle026 commented on tests/dictionaries/selectors.ts
> +// Exporta el diccionario de selectores como un objeto con una propiedad "selectors"
Se elimino el comentario

2023-04-21 22:40 UTC, Giselle026 commented on tests/dictionaries/selectors.ts
> + //login
Se elimino el comentario

2023-04-21 22:41 UTC, Giselle026 commented on tests/dictionaries/selectors.ts
> +// Exporta el objeto completo, si lo desea
Se elimino el comentario

2023-04-21 23:21 UTC, Giselle026 commented on tests/login/loginSiteAdmin.spec.ts
> +    await expect($(selectors.userName)).toBeExisting()
Sí, es necesario  el await porque es para validar la existencia del selector . También se menciona en la misma documentación oficial de webdriver.io el uso de Async/await https://webdriver.io/docs/async-migration/#async-transition.

2023-04-21 23:21 UTC, Giselle026 commented on tests/login/loginSiteAdmin.spec.ts
> +    await expect($(selectors.password)).toBeExisting()
Sí, es necesario  el await porque es para validar la existencia del selector . También se menciona en la misma documentación oficial de webdriver.io el uso de Async/await https://webdriver.io/docs/async-migration/#async-transition.

2023-04-21 23:21 UTC, Giselle026 commented on tests/login/loginSiteAdmin.spec.ts
> +    await $(selectors.userName).setValue(env.SITEADMIN_USERNAME)
Sí, es necesario  el await porque es para validar la existencia del selector . También se menciona en la misma documentación oficial de webdriver.io el uso de Async/await https://webdriver.io/docs/async-migration/#async-transition.

2023-04-21 23:22 UTC, Giselle026 commented on tests/login/loginSiteAdmin.spec.ts
> +    await $(selectors.password).setValue(env.SITEADMIN_PASSWORD)
Sí, es necesario  el await porque es para validar la existencia del selector . También se menciona en la misma documentación oficial de webdriver.io el uso de Async/await https://webdriver.io/docs/async-migration/#async-transition.

2023-04-21 23:22 UTC, Giselle026 commented on tests/login/loginSiteAdmin.spec.ts
> +    await $(selectors.bntLogin).click()
Sí, es necesario  el await porque es para validar la existencia del selector . También se menciona en la misma documentación oficial de webdriver.io el uso de Async/await https://webdriver.io/docs/async-migration/#async-transition.

2023-04-24 14:49 UTC, Giselle026 commented on tests/login/loginSiteAdmin.spec.ts
> +// @ts-ignore
Es por la extensión .ts por una razón VsCode lo reconoce como un problema pero sin ese .ts no reconoce los selectores del dicionarios y por eso está el comentario // @ts-ignore

2023-04-24 18:36 UTC, Giselle026 commented on tests/dictionaries/selectors.ts
> +    bntLogin           :'input[type="submit"]'
Observación corregida

2023-04-24 20:11 UTC, cancioalmaraza2o approved these changes

2023-04-24 20:11 UTC, merged