feature/RI-936
A2O-Dev/pfr-test-automation pull request #25
Opened 2023-05-22 13:34 UTC by Lino1998

2023-05-22 20:55 UTC, cancioalmaraza2o requested changes

2023-05-22 20:55 UTC, cancioalmaraza2o commented on tests/callbusinesslead/callbackRequested.spec.ts
> +    // Wait between tests
Eliminar comentario innecesario

2023-05-22 20:55 UTC, cancioalmaraza2o commented on tests/callbusinesslead/callbackRequested.spec.ts
> +    it('Wait between tests', async () => {
Es necesario hacer esta espera? no recuerdo haber visto esta necesidad en otro lado

2023-05-22 20:55 UTC, cancioalmaraza2o commented on tests/callbusinesslead/callbackRequested.spec.ts
> +        // Seleccionar y hacer clic en la fecha de hoy
Eliminar comentario innecesario.

Para este comentario sencillo, el código debe ser autodescriptivo

2023-05-22 20:55 UTC, cancioalmaraza2o commented on tests/callbusinesslead/callbackRequested.spec.ts
> +        // Click en el boton submit
Eliminar comentario

2023-05-22 20:55 UTC, cancioalmaraza2o commented on tests/callbusinesslead/callbackRequested.spec.ts
> +            timeoutMsg: 'El botón "Hoy" no apareció'
Cualquier mensaje que se muestre (si es realmente necesario), debe ser escrito en inglés

2023-05-22 20:55 UTC, cancioalmaraza2o commented on tests/callbusinesslead/callbackRequested.spec.ts
> +            timeoutMsg: 'La ventana emergente de selección de fecha no apareció'
Cualquier mensaje que se muestre (si es realmente necesario), debe ser escrito en inglés

2023-05-22 20:55 UTC, cancioalmaraza2o commented on tests/scheduledcalls/callScheduledContact.spec.ts
> +  // Wait between tests
Eliminar comentario innecesario

2023-05-22 20:55 UTC, cancioalmaraza2o commented on tests/scheduledcalls/callScheduledContact.spec.ts
> +  it('Wait between tests', async () => {
Es necesario esta espera? En términos generales y buenas prácticas de testings, este tiempo o proceso de espera no debería existir

2023-06-13 19:13 UTC, cancioalmaraza2o requested changes

2023-06-13 19:13 UTC, cancioalmaraza2o commented on tests/callbusinesslead/callbackRequested.spec.ts
Cambiar el nombre de la carpeta a "callBusinessLead"

2023-06-13 19:13 UTC, cancioalmaraza2o commented on tests/scheduledcalls/callScheduledContact.spec.ts
Cambiar nombre de carpeta a "scheduledCalls"

2023-06-13 19:13 UTC, cancioalmaraza2o commented on dictionaries/selectors/scheduledcalls.ts
Cambiar nombre del archivo a "scheduledCalls" y cambiar el nombre en el index.ts

2023-06-13 19:13 UTC, cancioalmaraza2o commented on tests/callbusinesslead/callbackRequested.spec.ts
Este comentario no ha sido resuelto

2023-06-13 19:13 UTC, cancioalmaraza2o commented on tests/scheduledcalls/callScheduledContact.spec.ts
Esta revisión no ha sido resuelta

2023-06-14 21:17 UTC, cancioalmaraza2o requested changes, later dismissed

2023-06-14 21:17 UTC, cancioalmaraza2o commented on tests/callbusinesslead/callbackRequested.spec.ts
Nuevamente, este comentario no ha sido resuelto

2023-06-14 21:17 UTC, cancioalmaraza2o commented on tests/scheduledcalls/callScheduledContact.spec.ts
Nuevamente, este comentario no ha sido resuelto

2023-06-14 21:17 UTC, cancioalmaraza2o commented on dictionaries/selectors/index.ts
> +export * from './donorManagement.js'
En dónde se encuentra este archivo actualmente¡ por qué lo añades y no se ve el archivo dentro de los archivo integrados?

Pdta: Estamos trabajando en typescript, por tanto todos los archivos deben llevar la extensión ".ts"

2023-06-15 23:11 UTC, GerardoA2o requested changes

2023-06-15 23:11 UTC, GerardoA2o commented on tests/callBusinessLead/callbackRequested.spec.ts
> +        await $('.xdsoft_datetimepicker').waitForClickable()
abstraer este selecctor al diccionario

2023-06-15 23:11 UTC, GerardoA2o commented on tests/callBusinessLead/callbackRequested.spec.ts
> +        expect(await $('.xdsoft_datetimepicker')).toBeExisting()
abstraer este selector al diccionario de selectores, todo funcion detro de de una funcion asincrona debe tener await 
por lo tanto previo al expect -> **await expect** ... de igual manera el selector debe tener su **await**

2023-06-15 23:11 UTC, GerardoA2o commented on tests/callBusinessLead/callbackRequested.spec.ts
> +        const todayCell = await $(`td[data-date="${todayDate}"].xdsoft_today`)
abstraer este selecctor al diccionario

2023-06-15 23:11 UTC, GerardoA2o commented on tests/scheduledCalls/callScheduledContact.spec.ts
> +      return (await $('.nameAndCompany .company').isDisplayed())
abstraer este selecctor al diccionario

2023-06-15 23:11 UTC, GerardoA2o commented on tests/scheduledCalls/callScheduledContact.spec.ts
> +    const companyCall = await $('.nameAndCompany .company').getText()
abstraer este selecctor al diccionario

2023-06-15 23:11 UTC, GerardoA2o commented on tests/scheduledCalls/callScheduledContact.spec.ts
> +    const nameCall = await $('.donorName').getText()
abstraer este selecctor al diccionario

2023-06-15 23:11 UTC, GerardoA2o commented on tests/scheduledCalls/callScheduledContact.spec.ts
> +    expect(companyContText).toHaveTextContaining(companyCall)
agregar await

2023-06-15 23:11 UTC, GerardoA2o commented on tests/scheduledCalls/callScheduledContact.spec.ts
> +    expect(nameContText).toHaveTextContaining(nameCall)
agregar await

2023-06-29 19:21 UTC, Lino1998 commented on tests/callBusinessLead/callbackRequested.spec.ts
> +        const todayCell = await $(`td[data-date="${todayDate}"].xdsoft_today`)
Tengo una pregunta como Abstraería este selector dentro del diccionario si dentro de este se esta llamando la constante todayDate?

2023-06-30 20:31 UTC, GerardoA2o approved these changes

2023-06-30 20:33 UTC, GerardoA2o approved these changes

2023-06-30 20:34 UTC, merged